name: Laravel Dusk Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  dusk-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: portal_inspektorat_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql --host=127.0.0.1 --port=3306 -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS portal_inspektorat_testing;"

    - name: Setup Environment
      run: |
        echo "APP_ENV=testing" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=portal_inspektorat_testing" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=password" >> .env

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      run: php artisan dusk:chrome-driver --detect

    - name: Start Laravel Server
      run: php artisan serve &
      env:
        APP_URL: "http://127.0.0.1:8000"

    - name: Run Dusk Tests
      run: php artisan dusk --without-tty
      env:
        APP_URL: "http://127.0.0.1:8000"

    - name: Upload Screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots
        path: tests/Browser/screenshots

    - name: Upload Console Logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: console-logs
        path: tests/Browser/console